# Site settings
title: The Brasscannon
email: skip@thebrasscannon.com
description: > # this means to ignore newlines until "baseurl:"
  Family Laihonen personal website. Stories, images and other stuff by Petri, Saku and Charlotte. 
  We currently live in a beautiful city of Helsinki, Finland.
copyright : > #
  All pages on this site are Copyright (c) 2001, Paul Newfield III. All rights reserved. Commercial use of this information is strictly prohibited without the specific written authorization of the owners.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://thebrasscannon.com" # the base hostname & protocol for your site
twitter_username: ""
github_username:  ""

# Build settings
markdown: kramdown

encoding: UTF-8
timezone: Europe/Helsinki
exclude: ['Gemfile', 'Gemfile.lock']
sass:
  sass_dir: '_sass'
navigation:
      - text: Home
        url: /
